# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  build:
    cmds:
      - go build -o ./out/bin/ght .
  install:
    cmds:
      - task build && cp ./out/bin/ght ~/go/bin/
